### ISSUE TITLE
RFC: Unable to see image topic_progression_graph.jpg

### ISSUE THREAD

**Issue by navoditjain-cricinfo** [ossu/data-science#103]
**Problem:**

I am unable to access or download the image [topic_progression_graph.jpg](https://github.com/ossu/data-science/blob/master/topic_progression_graph.jpg).

**Proposal:**
Request you to update the image or share it in this tread so we can follow the curriculum.

**Comment by waciumawanjohi** [comment]
You've linked to the file, which exists and is hosted here on github. Perhaps you should try [cloning the repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository). If you need more help, try reaching out to folks [on the Discord](https://discord.gg/wuytwK5s9h).
