### ISSUE TITLE
All Single Variable Calculus section links lead to 404

### ISSUE THREAD

**Issue by yoavami** [ossu/data-science#106]
All the links in the "Single Variable Calculus" section lead to 404. The right links need to be found and the README.md needs to be updated accordingly.

**Comment by waciumawanjohi** [comment]
Thanks for catching this! Commented on the open PR with working links to the MIT classes.

The PR currently open would switch the recommendation away from MIT calculus. Switching away from MIT courses would require a Request for Comments detailing the disadvantages of the MIT courses and the advantages of the proposed course. This would not be a small undertaking:
1. OSSU has a number of curricula and has been slowly working on standardizing recommendations across them. E.g. if there's no good reason for variation, the calc course for computer science should be the same as the calc course for data science.
2. Quite a bit of past analysis went into the choice of MIT calculus. This does not mean that it cannot be changed, but a proposal to change should be aware of and reference those past discussions. Good links to begin with:
  - https://github.com/ossu/computer-science/issues/465
  - https://github.com/ossu/computer-science/issues/838

If you've found a calculus course that's much better and will improve student learning, please open that RFC and let's get the best resources in front of OSSU students.
