### ISSUE TITLE
I can't enroll in the Udacity course on Descriptive Statistics I have checked using multiple accounts.

### ISSUE THREAD

**Issue by reallyyy** [ossu/data-science#111]
Every time I try to enroll I will be redirected into the My Programs page.

**Comment by waciumawanjohi** [comment]
The course appears open:
<img width="429" alt="image" src="https://github.com/ossu/data-science/assets/18407643/6cfee8a3-b482-4f1e-884b-37acd5e69af5">


Have you reached out to [Udacity Support](https://www.udacity.com/contact)?

**Comment by reallyyy** [comment]
It's open but I can't enroll into the course or access the course's content. Have you tried to access the course's content with a new account?

**Comment by reallyyy** [comment]
It has been 10 hours and they haven't got back and the issue still persists, would you mind checking the program yourself using a new account? I can enroll in the Intro to Inferential Statistics course it's the descriptive Statistics course that's the problem.

**Comment by waciumawanjohi** [comment]
If the course is no longer being offered, we'll need to go through at least a month long process to replace it with a course that is still on offer. It is therefore worth waiting a bit to see how Udacity responds.

**Comment by reallyyy** [comment]
Thank you for the respond. It's so weird considering the prerequiste of the Inferential Statistics course on Udacity is the descriptive Statistics course. Udacity should have both of them offer at the same time, not just one of them, so I think the problem can be something else. Let's just wait.

**Comment by reallyyy** [comment]
So they won't respond to my request and currently when you try to access the course through the link on github, it will return 404, it seems like they have removed the course.

**Comment by waciumawanjohi** [comment]
Thanks for staying on top of this issue. You've prompted me to open an issue to [overhaul the stats recommendations](https://github.com/ossu/data-science/issues/112).
