### ISSUE TITLE
Add Kaggle ML courses

### ISSUE THREAD

**Issue by TypicallyThomas** [ossu/data-science#113]
Kaggle has a lot of different ML and AI courses. Definitely worth a listing
https://www.kaggle.com/learn

**Comment by waciumawanjohi** [comment]
If there is a particular Kaggle course that meets the needs set forth in our curricular guidelines, please create an issue to discuss it. This may be either an area of our curricular guidelines that are not currently being met by the curriculum or a course that is better than the currently recommended course.
