### ISSUE TITLE
RFC: Proposal to Replace Princeton's DSA with Georgia Tech's CS 1332 Series in Data Science Curriculum

### ISSUE THREAD

**Issue by tuskydev** [ossu/data-science#121]
**Problem:**
- Proposing the 4-course CS 1332 Data Structures and Algorithms course from Georgia Tech over the current 2-part Princeton's DSA in the **Data Science Curriculum**: https://www.edx.org/certificates/professional-certificate/gtx-data-structures-and-algorithms 

**Duration:**
- 2024 April 28

**Background:**
- It includes a great **visual tool** to visualize all the data structures it covers: https://csvistool.com/
- The TA's for the Princeton courses have **announced they will not** keep supporting students who ask questions on the forums
- Georgia Tech's CS 1332 not only has active TA's in the edX forums but **has a discord server** where one can lean on for help from actual students at GT
- The instructor for all 4 courses, Mary H-B, has great 8-10min videos, and **doesn't read off the slides** (unlike Princeton)
- Princeton _forces_ the student to use the school's **proprietary libraries and download specific IDE's** for their course; OSSU students have complained about this but the people I've heard state their opinions on this are few

**Proposal:**
- The 4 courses are equal to one semester total at Georgia Tech
- CS1332x I-IV on the edX platform:
  - [CS 1332x I](https://www.edx.org/learn/data-structures/the-georgia-institute-of-technology-data-structures-algorithms-i-arraylists-linkedlists-stacks-and-queues)
  - [CS 1332x II](https://www.edx.org/learn/data-structures/the-georgia-institute-of-technology-data-structures-algorithms-ii-binary-trees-heaps-skiplists-and-hashmaps)
  - [CS 1332x III](https://www.edx.org/learn/data-structures/the-georgia-institute-of-technology-data-structures-algorithms-iii-avl-and-2-4-trees-divide-and-conquer-algorithms)
  - [CS 1332x IV](https://www.edx.org/learn/data-structures/the-georgia-institute-of-technology-data-structures-algorithms-iv-pattern-matching-dijkstras-mst-and-dynamic-programming-algorithms)

**Alternatives:**
1. Stick with the status quo
2. Replace the Princeton course with an alternative
3. Look for a Python course alternative; though hasn't been done in years (looking at previous RFC's)

_Thoughts are highly appreciated, don't hold back! Thank you 🙏🏼_

**Comment by tuskydev** [comment]
**PS:** 
- The 4-courses listed are equivalent to one class for one semester total at Georgia Tech

**Comment by waciumawanjohi** [comment]
The comment period has ended with support expressed by a few individuals, including a frequent contributor. @tuskydev Please open a PR to enact this change!

**Comment by tuskydev** [comment]
Will do! Thanks a lot
