### ISSUE TITLE
RFC: Add "The Essential Machine Learning Foundations: Math, Probability, Statistics, and Computer Science" by Jon Krohn

### ISSUE THREAD

**Issue by madhavi-peddireddy** [ossu/data-science#123]
**Description:**
The video collection "The Essential Machine Learning Foundations: Math, Probability, Statistics, and Computer Science" by Jon Krohn, released in March 2022, presents a comprehensive set of courses aimed at solidifying the foundational knowledge required for successful engagement in machine learning (ML) and data science. This issue addresses the potential integration of this resource into our curriculum and highlights its alignment with our curricular guidelines.

**Course Link:** [https://www.oreilly.com/library/view/the-essential-machine/9780137903245/](url)
**Github Repository:** [https://github.com/jonkrohn/ML-foundations](url)

**Steps to Reproduce:**

Review the content of each course within "The Essential Machine Learning Foundations" video collection.
Assess the alignment of the topics covered in these courses with our curricular guidelines for data science education.
Evaluate the quality and depth of instruction provided by Jon Krohn in each course.
Determine the suitability of integrating this video collection into our curriculum to enhance the foundational knowledge of our learners.

**Comment by pulkitkrishna00** [comment]
The proposed courses are paid, and the platform hosting them only provides a 10 day free tral and no way to audit courses for free. As such, these courses do not fulfil the OSSU criteria.
