### ISSUE TITLE
RFC: Update Math Course Links from OpenLearningLibrary to MITx Online

### ISSUE THREAD

**Issue by Ad7amstein** [ossu/data-science#131]
**Problem:**
OSSU currently lists math courses on OpenLearningLibrary, but the same courses are available on MITx Online, which includes problem sets that enhance the learning experience. This issue means the current links do not fully leverage the available resources that better align with OSSU's curricular guidelines, especially in providing rigorous and comprehensive course material.

It is important to note that the problem sets on MITx Online are not graded since the due date for the courses has passed. However, they still serve as valuable practice for students looking to deepen their understanding of the material.

**Proposal:**
- Update the link for **Calculus 1A: Differentiation** to [MITx Online](https://mitxonline.mit.edu/courses/course-v1:MITxT+18.01.1x/).
- Update the link for **Calculus 1B: Integration** to [MITx Online](https://courses.mitxonline.mit.edu/learn/course/course-v1:MITxT+18.01.2x+3T2023/home).
- Update the link for **Calculus 1C: Coordinate Systems & Infinite Series** to [MITx Online](https://mitxonline.mit.edu/courses/course-v1:MITxT+18.01.3x/).
- The necessary changes have been proposed in [Pull Request #130](https://github.com/ossu/data-science/pull/130).

**Alternatives:**
- Continue using the OpenLearningLibrary links without the problem sets.
- Offer both links and allow students to choose between the OpenLearningLibrary and MITx Online versions.

**Comment by waciumawanjohi** [comment]
MIT has been great in making courses available online and in updating them. But the movement between platforms (and the plethora of platforms) has made these updates difficult to track. @Ad7amstein Can you contextualize your recommendation with the earlier discussions choosing between MIT platforms?
- https://github.com/ossu/computer-science/issues/838
- https://github.com/ossu/computer-science/issues/886

(e.g. Is the MITx platform newer than those discussions? Are there resources on MITx that weren't/aren't available on the others?)

**Comment by pulkitkrishna00** [comment]
Yes, the MITx platform is newer. The courses themselves are the same as those that were present previously on Edx. They just moved from Edx to MITx (MITx runs on the self-hosted version of Edx). So, most things said about the Edx version of the course in those previous discussion hold true for the MITx version as well.
