### ISSUE TITLE
Capstone in Coursera and Nanodegree of Udacity are not free.

### ISSUE THREAD

**Issue by saip009** [ossu/data-science#26]
As far as I know inn Coursera however all courses from the specialization except for the capstone project can be found and enrolled separately. And to access the capstone project, you need to get certification from all other courses from the specialization.
Also on Udacity the nano degree programs are not free.

I think you should add these points in the introduction as many people may think all those specializations are free. Unless I'm wrong in which case I would like to know what's the procedure of accessing them for free.

Thanks

**Comment by anithp** [comment]
ok i will make the change,
Thank you,
Regards,
Anith Patel
