### ISSUE TITLE
Fixing the link of Probability and Statistics

### ISSUE THREAD

**Issue by abhinav1592** [ossu/data-science#29]
The link "Probability and Statistics with R" currently points to 
https://github.com/open-source-society/data-science#probability-and-statistics-with-r

But the section "Probability and Statistics with R"  has href "#probability-and-statistics".
Either of them need to be changed.
===================================================================
I am learning to contribute. Please help me out in creating a pull request because I want to fix the issue myself. I want this to be my first contribution towards open-source.

**Comment by DaniAkash** [comment]
Hmm... 
* Click the `README.md` file in the repository to open it's full preview
* Click edit icon on top right corner of the file
* Replace `#probability-and-statistics-with-r` with `#probability-and-statistics` along with other changes u wish.

Then click propose file changes where it will take you to create your own pull request.

**Comment by DaniAkash** [comment]
Oh also in the description section, make sure to add _**fixes open-source-society/data-science#29**_ keyword, so that your issue will be closed when the pull request is merged!

**Comment by waciumawanjohi** [comment]
Closing this issue as there is a proposed change that will address these issues. Comment here: #61
