### ISSUE TITLE
a lot of Python Courses

### ISSUE THREAD

**Issue by MohammedAttya2** [ossu/data-science#31]
There is 4 courses for Python, it's more than enough
2 Courses 4 probability
and more duplicated courses
Please refactor the content like Computer Science track

**Comment by SUSHANT12PRABHU** [comment]
can you be more specific please?

**Comment by datatalking** [comment]
guys lets think about how little most people know the language and how much there is to know

**Comment by PeterMTaylor** [comment]
Taking into consideration how Python is perceived to be helpful being part of being integrated with Microsoft Excel. https://excel.uservoice.com/forums/304921-excel-for-windows-desktop-application/suggestions/10549005-python-as-an-excel-scripting-language
