### ISSUE TITLE
probability courses not available

### ISSUE THREAD

**Issue by tjefferies** [ossu/data-science#37]
Love the curriculum so far! Only complaint is that the edX offerings of the following courses are not currently available:
- [Introduction to Statistics: Descriptive Statistics](https://www.edx.org/course/introduction-statistics-descriptive-uc-berkeleyx-stat2-1x)
- [Introduction to Statistics: Probability](https://www.edx.org/course/introduction-statistics-probability-uc-berkeleyx-stat2-2x)
- [Introduction to Statistics: Inference](https://www.edx.org/course/introduction-statistics-inference-uc-berkeleyx-stat2-3x)

Any suggestions for similar courses?

**Comment by waciumawanjohi** [comment]
Closing this issue as there is a proposed change that will address these issues. Comment here: #61
