### ISSUE TITLE
5 years duration !

### ISSUE THREAD

**Issue by maboulfotouh** [ossu/data-science#42]
i just calculated the duration for all courses and it was 5 years ! :smile:

**Comment by datatalking** [comment]
Well yeah, so don't go that slow, take one or two at a time.

**Comment by royshouvik** [comment]
@maboulfotouh Isn't it beautiful that we have so much available at our fingertips to learn from? I wish MOOCs existed when I was in school/university. 

Also, it's not so much about the destination, but the journey. 🎯
