### ISSUE TITLE
Linear Algebra

### ISSUE THREAD

**Issue by ZRupp** [ossu/data-science#44]
Is there not a better Linear Algebra course? This LAFF course is painfully obtuse and dull.

**Comment by JunyiJ** [comment]
I think the MIT linear algebra course is pretty good(https://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/), but the quality of the video is not so good.

**Comment by waciumawanjohi** [comment]
Closing this issue as there is a proposed change that will address these issues.

The proposed Linear Algebra course is MIT's OCW Scholar course: https://ocw.mit.edu/courses/mathematics/18-06sc-linear-algebra-fall-2011/

Comment here: https://github.com/ossu/data-science/issues/61
