### ISSUE TITLE
Who is working on the data science coursework

### ISSUE THREAD

**Issue by datatalking** [ossu/data-science#45]
How can I help, this is so close to the existing project I'm working on that I would like to volunteer to take this over unless someone else is actively working on this.

**Comment by m-escobar** [comment]
Just started that one.

**Comment by Alaharon123** [comment]
@royshouvik as it says on the bottom of the readme

**Comment by royshouvik** [comment]
@datatalking I have been focusing on other stuff and haven't got a chance to take a look at the data science curriculum. Please let me know if you are interested in maintaining and taking the curriculum forward 🙏 .

**Comment by datatalking** [comment]
I am, is there a main "how stuff works" regarding the site. Who is supplies the hosting and so forth? We are updating it shortly in February with more content.

**Comment by MarcosZucco** [comment]
I am stuying the data science content

**Comment by nchibuzo74** [comment]
I am studying data science using python

**Comment by tanvirstreame** [comment]
I have course of data science

**Comment by teddiconfetti** [comment]
I’m here studying the data science content
