### ISSUE TITLE
Probability and Statistics Courses not available

### ISSUE THREAD

**Issue by odarotto** [ossu/data-science#46]
The 3 last courses in this section aren't available: 

 https://www.edx.org/course/introduction-statistics-descriptive-uc-berkeleyx-stat2-1x
https://www.edx.org/course/introduction-statistics-probability-uc-berkeleyx-stat2-2x
https://www.edx.org/course/introduction-statistics-inference-uc-berkeleyx-stat2-3x

**Comment by sudheerrakasi** [comment]
seems like the course is not available yet , are there any substitute links/courses that we can take ?

**Comment by sudheerrakasi** [comment]
thank you very much for the info

**Comment by waciumawanjohi** [comment]
Closing this issue as there is a proposed change that will address these issues. Comment here: https://github.com/ossu/data-science/issues/61
