### ISSUE TITLE
SDK update required to sign up via Web App

### ISSUE THREAD

**Issue by VidyaPriyadarshini** [ossu/data-science#48]
Steps to reproduce
Navigate to https://ossu.firebaseapp.com/#/
Click Login with Github
Error Message encountered: {"code":"SERVICE_UNAVAILABLE","statusCode":410,"message":"SDK Update Required: See https://goo.gl/2cKQWm.","details":"SDK Update Required: https://goo.gl/2cKQWm. "}
More details on updating the SDK as of December 2018 is given in below google doc.
https://docs.google.com/document/d/1vpQV8DBQLkIZci7Vh8N4LUHyTkBOsuW5eXE1x8IAqvw/edit?usp=sharing

Would like to know if we can update the SDK as per above instructions. Thanks

**Comment by mehrdadpfg** [comment]
is this repo outdated?

**Comment by waciumawanjohi** [comment]
Sadly, the maintainer of that app has abandoned it without giving anyone else access. Link to the app has been removed in this commit:
https://github.com/ossu/data-science/commit/274cd0b951594cf75dc6b00d01277150695db5cf
