### ISSUE TITLE
Q: How long does this program typically take?

### ISSUE THREAD

**Issue by wanageeska** [ossu/data-science#53]
Hi, sorry if this is the wrong place to post this question but I can’t seem to find an answer. What is the typical duration for the ossu data science course (assuming a full-time study load)? Thanks!

**Comment by waciumawanjohi** [comment]
There is an open Request for Comments that will change the curriculum significantly, making it difficult to answer this question at the moment. I encourage you to join the OSSU Discord server to chat with other students there and hear their experience. https://discord.gg/tgfXKzZ
