### ISSUE TITLE
Trello Board 

### ISSUE THREAD

**Issue by BenjaminTrainorJS** [ossu/data-science#77]
When accessing the Data Science Trello Board, and you click on the menu.. we are unable to copy the board.

**Comment by waciumawanjohi** [comment]
I was able to copy it just now. One unexpected step, when I clicked on Menu, it automatically opened the "About This Board" choice. I just pressed the back arrow (right next to the text "About This Board") and it took me back to the full menu. Then I was able to follow the instructions [here](https://help.trello.com/article/802-copying-cards-lists-or-boards).

**Comment by nohhhon** [comment]
Command_ultra_prompt🌐

**Comment by nohhhon** [comment]
> When accessing the Data Science Trello Board, and you click on the menu.. we are unable to copy the board. 

Try using webtest browser. Dev settings.. script compatibility

**Comment by nohhhon** [comment]
[Webview [test ] ***@***.***

Thats a huge amount of electricity..
https://www.instagram.com/p/B1BARz3pIWQ/?igshid=15ihvdyc02zxz
