### ISSUE TITLE
Add a specialization section on AI

### ISSUE THREAD

**Issue by SamiulHasnatTaseen** [ossu/data-science#90]

**Comment by waciumawanjohi** [comment]
Your suggestion is noted.

I will point out that artificial intelligence is not mentioned in the data science standards that OSSU:DS uses ([Curriculum Guidelines for Undergraduate Programs in Data Science](https://www.amstat.org/asa/files/pdfs/EDU-DataScienceGuidelines.pdf)) A more appropriate place to look is in the Computer Science curriculum. You can see an open issue here where an AI specialization is being created.
